# Generated by Django 3.2.6 on 2021-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('highschool', models.CharField(max_length=70)),
                ('degree', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('skill', models.TextField(max_length=1000)),
                ('about_you', models.TextField(max_length=1000)),
                ('previous_work', models.TextField(max_length=1000)),
            ],
        ),
    ]
