# Generated by Django 3.2.6 on 2021-09-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
